# Generated by Django 3.0.6 on 2020-05-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='displayname',
            field=models.CharField(default='Please enter a displayname', max_length=50),
            preserve_default=False,
        ),
    ]
